### ISSUE TITLE
api default patch is still 6.84b

### ISSUE THREAD

**Issue by KavenTheriault** [JankGaming/herostats-api#1]
The api can give 6.84c info if you specify the patch 6.84c like this "http://api.herostats.io/patch/6.84c",
but if you directly get the hero info "http://api.herostats.io/heroes/Bristleback", the api give you the 6.84b info.

**Comment by twisterghost** [comment]
Thanks, this has been fixed on the live API. Querying without a patch should give you the 6.84c now.
